[book]
authors = ["ewof"]
language = "en"
src = "src"
title = "Mvndicraft"

[output.html]
mathjax-support = true
preferred-dark-theme = "ayu"
additional-css = ["theme/custom.css"]
additional-js = ["theme/custom.js"]

[output.html.print]
enable = false
