
  # -- One Ingredient: --
  wheat:
    name: Fermented wheat
    ingredients: Wheat
    cookParticles:
      - '2d8686/8' # Dark Aqua

  sugarcane:
    name: Sugar brew
    ingredients: Sugar_Cane
    color: 'f1ffad' # yellowish green
    cookParticles:
      - 'f1ffad/4'
      - '858547/10' # dark olive

  sugar:
    name: Sugarwater
    ingredients: Sugar
    cookParticles:
      - 'WHITE/4'
      - 'BRIGHT_GREY/25'

  apple:
    name: Apple must
    ingredients: Apple

  berries:
    name: Grape must
    ingredients: Sweet_Berries
    color: RED
    cookParticles:
      - 'ff6666/2' # bright red
      - 'RED/7'
      - 'ac6553/13' # brown-red

  potato:
    name: Potatomash
    ingredients: Potato

  grass:
    name: Boiled herbs
    ingredients: Grass
    color: '99ff66' # bright green
    cookParticles:
      - 'GREEN/2'
      - '99ff99/20' # faded green

  rmushroom:
    name: Mushroom brew
    ingredients: Red_Mushroom
    color: 'ff5c33' # amber red
    cookParticles:
      - 'fab09e/15' # faded red

  bmushroom:
    name: Mushroom brew
    ingredients: Brown_Mushroom
    color: 'c68c53' # brighter brown
    cookParticles:
      - 'c68c53/15'

  cocoa:
    name: Chocolately brew
    ingredients: Cocoa_Beans
    color: '804600' # mocca
    cookParticles:
      - 'a26011/1'
      - '5c370a/3'
      - '4d4133/8' # Gray-brown

  milk:
    name: Milky water
    ingredients: Milk_Bucket
    color: BRIGHT_GREY
    cookParticles:
      - 'fbfbd0/1' # yellow-white
      - 'WHITE/6'

  bl_flow:
    name: Blueish brew
    ingredients: blue-flowers
    color: '0099ff' # sky blue
    cookParticles:
      - '0099ff'

  cactus:
    name: Agave brew
    ingredients: cactus
    color: '00b300' # cactus green
    cookParticles:
      - '00b300/16'

  poi_potato:
    name: Poisonous Broth
    ingredients: Poisonous_Potato

  egg:
    name: Sticky brew
    ingredients: Egg


  oak_sapling:
    name: Stringy hebry broth
    ingredients: Oak_Sapling

  vine:
    name: Boiled herbs
    ingredients: vine
    color: '99ff66' # bright green
    cookParticles:
      - 'GREEN/2'
      - '99ff99/20' # faded green

  rot_flesh:
    name: Foul pest
    ingredients: Rotten_Flesh
    color: '263300' # brown green
    cookParticles:
      - '263300/8'
      - 'BLACK/20'

  melon:
    name: Melon juice
    ingredients: melon_slice

  wheat_seeds:
    name: Bitter brew
    ingredients: Wheat_Seeds

  melon_seeds:
    name: Bitter brew
    ingredients: Melon_Seeds

  pumpkin_seeds:
    name: Bitter brew
    ingredients: Pumpkin_Seeds

  bone_meal:
    name: Bony Brew
    ingredients: bone_meal
    color: BRIGHT_GREY

  cookie:
    name: Chocolately sap
    ingredients: Cookie
    color: '804600' # mocca
    cookParticles:
      - 'a26011/1'
      - '5c370a/3'
      - '4d4133/8' # Gray-brown

  fer_spid_eye:
    name: Fermented Eye
    ingredients: Fermented_Spider_Eye

  ghast_tear:
    name: Sad brew
    ingredients: ghast_tear

  snowball:
    name: Icewater
    ingredients: Snowball

  Gold_Nugget:
    name: Glistering brew
    ingredients: Gold_Nugget
    color: 'ffd11a' # gold
    cookParticles:
      - 'ffd11a'

  glowstone_dust:
    name: Glowing brew
    ingredients: Glowstone_Dust
    color: 'ffff33' # bright yellow
    cookParticles:
      - 'ffff99/3'
      - 'd9d926/15' # faded yellow

  # -- Multiple Ingredients: --
  applemead_base:
    name: Apple-Sugar brew
    ingredients:
      - Sugar_Cane/3
      - Apple
    color: 'e1ff4d' # greenish yellow
    cookParticles:
      - 'e1ff4d/4'

  poi_grass:
    name: Boiled acidy herbs
    ingredients:
      - Grass
      - Poisonous_Potato
    color: '99ff66' # bright green
    cookParticles:
      - 'GREEN/2'
      - '99ff99/20' # faded green

  juniper:
    name: Juniper brew
    ingredients:
      - blue-flowers
      - wheat
    color: '00ccff' # aqua
    cookParticles:
      - '00ccff/8'

  gin_base:
    name: Fruity juniper brew
    ingredients:
      - blue-flowers
      - wheat
      - apple
    color: '66e0ff' # lighter aqua
    cookParticles:
      - '00ccff/5'


# -- Recipes for Potions --


  wheatbeer:
    name: Skunky Wheatbeer/Wheatbeer/Fine Wheatbeer
    ingredients:
      - Wheat/3
    cookingtime: 8
    distillruns: 0
    wood: 1
    age: 2
    color: 'ffb84d' # Orange
    difficulty: 1
    alcohol: 5
    lore: +++ &8Refreshing

  beer:
    name: Skunky Beer/Beer/Fine Beer
    ingredients:
      - Wheat/6
    cookingtime: 8
    distillruns: 0
    wood: 0
    age: 3
    color: 'ffd333' # Bright Orange
    difficulty: 1
    lore:
      - +++ &8Crisp taste
    alcohol: 6

  darkbeer:
    name: Skunky Darkbeer/Darkbeer/Fine Darkbeer
    ingredients:
      - Wheat/6
    cookingtime: 8
    distillruns: 0
    wood: 6
    age: 8
    color: '650013' # Dark Red-Brown
    difficulty: 2
    lore:
      - +++ &8Roasted taste
    alcohol: 7

  wine:
    name: Red Wine
    ingredients:
      - Sweet_Berries/5
    cookingtime: 5
    distillruns: 0
    wood: 0
    age: 20
    color: RED
    difficulty: 4
    alcohol: 8
    lore:
      - '+ &8Harsh'
      - '+ &8Corked'
      - '++ &8Mellow'
      - '+++ &8Full-Bodied'

  mead:
    name: Awkward Mead/Mead/&6Golden Mead
    ingredients:
      - Sugar_Cane/6
    cookingtime: 3
    distillruns: 0
    wood: 2
    age: 4
    color: ORANGE
    difficulty: 2
    lore:
      - +++ Has a golden shine
    alcohol: 9

  ap_mead:
    name: Apple Mead/Sweet Apple Mead/&6Sweet Golden Apple Mead
    ingredients:
      - Sugar_Cane/6
      - Apple/2
    cookingtime: 4
    distillruns: 0
    wood: 2
    age: 4
    color: ORANGE
    difficulty: 4
    alcohol: 11
    lore:
      - +Is there any Apple in this?
      - ++Refreshing taste of Apple
      - +++Sweetest hint of Apple
    effects:
      - WATER_BREATHING/1-2/150

  cidre:
    name: Poor Cidre/Apple Cider/Great Apple Cider
    ingredients:
      - Apple/14
    cookingtime: 7
    distillruns: 0
    wood: 0
    age: 3
    color: 'f86820' # Red-Orange
    difficulty: 4
    alcohol: 7

  apple_liquor:
    name: Sour Apple Liquor/Apple Liquor/Calvados
    ingredients:
      - Apple/12
    cookingtime: 16
    distillruns: 3
    wood: 5
    age: 6
    color: BRIGHT_RED
    difficulty: 5
    alcohol: 14
    lore:
      - +Sour like Acid
      - +++ Good Apple Liquor

  vodka:
    name: Lousy Vodka/Vodka/Russian Vodka
    ingredients:
      - Potato/10
    cookingtime: 15
    distillruns: 3
    age: 0
    color: WHITE
    difficulty: 4
    alcohol: 20
    lore: + &8Almost undrinkable
    effects:
      - WEAKNESS/15
      - POISON/10

  shroom_vodka:
    name: Mushroom Vodka/Mushroom Vodka/Glowing Mushroom Vodka
    ingredients:
      - Potato/10
      - Red_Mushroom/3
      - Brown_Mushroom/3
    cookingtime: 18
    distillruns: 5
    age: 0
    color: 'ff9999' # Pink-Red
    difficulty: 7
    alcohol: 18
    lore: +++&aGlows in the dark
    effects:
      - WEAKNESS/80
      - CONFUSION/27
      - NIGHT_VISION/50-80
      - BLINDNESS/12-2
      - SLOW/10-3

  absinthe:
    name: Poor Absinthe/Absinthe/Strong Absinthe
    ingredients:
      - Grass/15
    cookingtime: 3
    distillruns: 6
    distilltime: 80
    color: GREEN
    difficulty: 8
    alcohol: 42
    effects:
      - POISON/15-25
    lore: '+++&8High proof liquor'

  gr_absinthe:
    name: Poor Absinthe/Green Absinthe/Bright Green Absinthe
    ingredients:
      - Grass/17
      - Poisonous_Potato/2
    cookingtime: 5
    distillruns: 6
    distilltime: 85
    color: LIME
    difficulty: 9
    alcohol: 46
    effects:
      - POISON/25-40
      - HARM/2
      - NIGHT_VISION/40-60
    lore: '&aLooks poisonous'

  potato_soup:
    name: Potato soup
    ingredients:
      - Potato/5
      - Grass/3
    cookingtime: 3
    color: ORANGE
    difficulty: 1
    effects:
      - HEAL/0-1

